# Generated by Django 3.2.7 on 2021-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20211023_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='Certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='historicalhackathon',
            name='Certificate',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhackathon',
            name='image1',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhackathon',
            name='image2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
